# -*- coding: utf-8 -*-
"""GroupProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1667a--1Q4yTrZXHv39W-AubpmtDlsau3

# Data Science for Marketing group project
## Lisbon Attractions Reviews

_Client: Lisbon Tourism Authority_


(c) Nuno António 2025 - Rev. 1.00

## Work description

### Overview
Turismo de Lisboa (TLA) (see https://www.visitlisboa.com/en/about-turismo-lisboa) wants to transform Tripadvisor reviews of Lisbon’s attractions into actionable guidance for marketing. Your team will act as LTA’s analytics partner, using the CRISP-DM process to diagnose the visitor experience, quantify improvement levers (e.g., crowding, value for money, accessibility), and recommend concrete actions for the next season.

### Objectives
1. **Measure** city and attraction-level experience quality (ratings & sentiment) and how it evolves over time/season.  
2. **Diagnose** the key drivers of satisfaction/dissatisfaction (e.g., queues, price, cleanliness, interpretation quality).  
3. **Segment** visitors (e.g., by language/market or trip type) to tailor messages and on-site services.  
4. **Prioritize** interventions with an impact × effort view and produce a decision-ready roadmap.  
5. **(Optional)** Benchmark Lisbon against peer European cities or attraction categories if comparable data are available.

### Data (provided)
- `attraction_data_reviews.csv` — review-level dataset (text, rating, date, etc.)
- `attractions_data_metadata.csv` — attraction descriptors (category, location, hours, ticketing, etc.)
- `attractions_list.csv` — list of attractions to scope the study.

- **Reviews columns:** `title, text, rating, reviewer, visitMonth, country, visitType, contributions, likesNumber, replyText, replyDate, reviewDate, name, tripadvisorId, dateFirstCollection`
- **Metadata columns:** `tripadvisorId, name, location, latitude, longitude, dateFirstCollection, ratingGlobal, reviewCount, url, attractionCategory, rankingPositionAttractionCategory, totalRankingUnitsAttractionCategory`
- **Attractions list columns:** `name, url, tripadvisor_id, num_reviews`

### Key Business Questions
- What is the **overall satisfaction** by attraction and category? Which sites/companies are underperforming relative to peers and volume?
- How do **trends** vary by month/season, day of week, and (if available) hour? Where do negative spikes occur?
- Which **markets/languages** are most/least satisfied and why? What messages resonate in positive reviews?
- Where are the biggest **value-for-money** gaps and what product tweaks (e.g., guided tours, skip-the-line) improve perception?
- If we could make only **five interventions** next quarter, which would maximize impact?
- **(Optional)** Which themes most influence ratings (**crowding/queues, staff, cleanliness, price/value, accessibility, interpretation quality**)?
- **(Optional)** What **accessibility** or **safety/maintenance** issues recur, and at which sites?

### Method (CRISP-DM)
1. **Business Understanding**  
   Translate LTA goals into KPIs and hypotheses; define success criteria (see below).
2. **Data Understanding**  
   Inspect coverage, date range, languages, missingness; validate representativeness and potential biases.
3. **Data Preparation**  
   - Parse/standardize dates and ratings; unify attraction IDs/names.  
   - Text prep: cleaning, language detection, optional machine translation for comparability.  
4. **Modeling & Analysis**  
   - Descriptive: distributions, trends, peer-adjusted rankings.  
   - **(Optional)** NLP: topic modeling (e.g., BERTopic/LDA) and sentiment per topic.  
   - **(Optional)** Drivers: regressions/SHAP to quantify impact of themes on ratings.  
   - Segmentation: by language/market or trip type; optional “first-time vs repeat” heuristics.  
5. **Evaluation**  
   Sanity checks, back-testing stability over time, interpretability, and stakeholder review.  
6. **Deployment (Project Output)**  
   Reproducible notebook + dashboards/scorecards, and a prioritized action plan.

### Core KPIs (draft)
- **Overall Satisfaction Score (OSS):** weighted mean rating per attraction/month.  
- **(Optional)** **Topic Sentiment Score:** mean sentiment for themes (crowding, price, etc.).  
- **Crowding Pressure Index:** share of reviews mentioning wait/crowd × seasonal intensity.  
- **Accessibility Score:** ratio of positive vs negative accessibility mentions.  
- **Value for Money Index:** sentiment/ratings around price/value adjusted by price tier.  
- **Incident Rate:** safety/cleanliness issue mentions per 100 reviews.  
- **Experience Quality Index (city-level):** composite of OSS, Accessibility, and inverse of Crowding/Incidents.

### Risks, Ethics & Quality
- **Bias & Representativeness:** online reviews may over-represent certain markets/segments; report limitations.  
- **Language & Translation:** sentiment can shift with translation; validate on samples.  
- **Attribution:** correlations ≠ causation; be explicit about inference limits.  
- **Privacy:** use only public data; no attempt to deanonymize reviewers.

### Stretch Goals (time permitting)
- **Early-warning system** for emerging negative themes.  
- **Geospatial joins** (if coordinates available) to map pain points and access.  
- **Benchmarking** against EU peers using comparable categories/periods.

### Deliverables
- Python source code (Jupyter notebook or .py files) and/or Excel files
    - Python code should be commented on to facilitate comprehension
    - Remarks or Markup should be used to identify the different CRISP-DM phases, including Data understanding, Data preparation, among others
- Powerpoint presentation (targeting non-technical audience)
- Report (targeting non-technical audience):
    - Maximum of 20 pages (including appendixes)
    - Minimum font size is 10
    - Should include an executive summary, background/context, a brief description of the problem, brief description of the methods, results and their discussion, focusing on insights and calls to action marketing-wise

### Questions or additional information
Your practical-class instructors act as LTA stakeholders. Use them to refine hypotheses and pressure-test recommendations.

Good work—and have fun turning reviews into real-world improvements for Lisbon’s visitors and residents!

## Strategic Questions (What Lisbon Tourism Authority cares about)

Each question includes **Why it matters**, **How to answer**, and **Outputs**.

### 1) Visitor Satisfaction & Experience
- **Q1. What is the overall satisfaction by attraction and category?**
  - *Why:* Prioritize funding, maintenance, and promotion.
  - *How:* Star rating distribution; median/mean rating; confidence intervals.
  - *Outputs:* Ranked league tables; control charts; flag underperformers.
- **Q2. What are the top drivers of satisfaction and dissatisfaction?**
  - *Why:* Target root causes (e.g., staff, queues, cleanliness, price).
  - *How:* NLP on reviews (topic modeling + sentiment per topic); SHAP on rating regression.
  - *Outputs:* Driver importance chart; topic-sentiment heatmap; actionable themes list.
- **Q3. How do satisfaction levels change over time and season?**
  - *Why:* Anticipate seasonal pain points (crowding, heat).
  - *How:* Monthly time series of ratings and sentiment; change-point detection.
  - *Outputs:* Seasonal trend lines; alert on sudden drops.

### 2) Crowding, Capacity & Operations
- **Q4. Which attractions most frequently face overcrowding or queue complaints?**
  - *Why:* Queue management, timed entries, staffing, wayfinding.
  - *How:* Keyword/LLM tagging for “queue”, “wait”, “crowd”; topic frequency over time.
  - *Outputs:* Heatmap of crowding mentions; peak hours/days table.
- **Q5. What is the relationship between crowding mentions and ratings?**
  - *Why:* Quantify the cost of crowding on satisfaction.
  - *How:* Correlate topic intensity with ratings; causal proxy via panel models.
  - *Outputs:* Elasticity estimate; marginal impact plots.
- **Q6. When do negative experiences cluster (day of week, hour, month)?**
  - *Why:* Inform staggered opening hours or capacity caps.
  - *How:* Temporal features from review timestamps; seasonality decomposition.
  - *Outputs:* Calendar heatmaps; recommendations for schedule changes.

### 3) Market Segmentation & Source Markets
- **Q7. Which nationalities/language groups are most satisfied, and where are gaps?**
  - *Why:* Tailor information, signage, and campaigns.
  - *How:* Language detection; geo-inference from user profiles/text; per-segment KPIs.
  - *Outputs:* Segment scorecards; translation priorities.
- **Q8. How do first-time vs repeat visitors differ in needs and sentiment?**
  - *Why:* Product-market fit for newcomers vs loyalists.
  - *How:* Heuristics in text (“first time”, “again”); clustering.
  - *Outputs:* Experience journey differences; targeted messaging.

### 4) Value for Money & Pricing Perception
- **Q9. Where is “value for money” praised vs criticized?**
  - *Why:* Pricing policy, bundle passes, discounts.
  - *How:* Topic/sentiment on “price”, “expensive”, “worth it”.
  - *Outputs:* Value-perception map; elasticity proxies.
- **Q10. Which add-ons (guides, skip-the-line, audio) improve perceived value?**
  - *Why:* Optimize product packaging and upsells.
  - *How:* Co-mention analysis of add-on terms vs ratings delta.
  - *Outputs:* Bundle recommendations; ROI estimates (proxy).

### 5) Accessibility, Inclusivity & Safety
- **Q11. What accessibility issues are most reported (mobility, stroller, visual, audio)?**
  - *Why:* Compliance and inclusive tourism goals.
  - *How:* Keyword/LLM tagging (“wheelchair”, “lift”, “stairs”); sentiment by theme.
  - *Outputs:* Accessibility action list per attraction.
- **Q12. Are there safety, cleanliness, or maintenance concerns?**
  - *Why:* Public trust and reputation management.
  - *How:* Topic extraction for “theft”, “dirty”, “broken”; severity scoring.
  - *Outputs:* Incident trend dashboard; escalation alerts.

### 6) Content & Interpretation Quality
- **Q13. Do visitors find exhibits/descriptions engaging and clear?**
  - *Why:* Education outcomes; cultural heritage value.
  - *How:* Topic “guide”, “audio guide”, “exhibit”, “label”; sentiment & length.
  - *Outputs:* Content improvement backlog; language priorities.
- **Q14. Which tours or experiences receive the most praise/criticism?**
  - *Why:* Curate best-practice formats.
  - *How:* Entity extraction for tour types; compare ratings/sentiment.
  - *Outputs:* Top/bottom experiences; design patterns.

### 7) Journey to/around the Site
- **Q15. Are directions, transport links, and wayfinding adequate?**
  - *Why:* Reduce friction before arrival; distribute flows.
  - *How:* Mentions of “tram”, “bus”, “parking”, “signs”; geospatial joins.
  - *Outputs:* Map of transport pain points; signage recommendations.
- **Q16. What nearby amenities (food, restrooms, shade) need attention?**
  - *Why:* Onsite comfort and dwell time.
  - *How:* Co-mentions with amenity terms; sentiment analysis.
  - *Outputs:* Amenity gap list per site.

### 8) Benchmarking & Positioning
- **Q17. Which Lisbon attractions are over- or under-performing vs their peer group?**
  - *Why:* Fair comparisons drive better targets.
  - *How:* Peer sets by category/volume/price; z-scores; Bayesian shrinkage.
  - *Outputs:* Peer-adjusted ranking; watchlist.
- **Q18. How does Lisbon compare with European peers on similar categories?** *(optional if external benchmark available)*
  - *Why:* City-level positioning.
  - *How:* If comparable external data exist, mirror metrics vs EU peer cities.
  - *Outputs:* Competitive gaps; best-practice transfer.

### 9) Communications & Reputation
- **Q19. What messages resonate most in positive reviews?**
  - *Why:* Feed effective themes to campaigns.
  - *How:* Keyphrase extraction from 5-star reviews; n-grams.
  - *Outputs:* Messaging library by market.
- **Q20. Which negative narratives spread, and how to counter them?**
  - *Why:* Crisis prevention and response.
  - *How:* Track emerging topics with rising negative sentiment.
  - *Outputs:* Early-warning alerts; response playbooks.

### 10) Monitoring & Governance
- **Q21. Can we create a live quality-of-experience index for the city?**
  - *Why:* Ongoing performance management.
  - *How:* Composite index (ratings, crowding, safety, accessibility).
  - *Outputs:* Monthly dashboard; thresholds for intervention.
- **Q22. Where should Lisbon invest next quarter/year for maximum impact?**
  - *Why:* Allocate budget to the highest ROI fixes.
  - *How:* Impact × Effort matrix using driver importance and volume.
  - *Outputs:* Prioritized roadmap with costed actions (estimates).

## Methodology Overview (how to answer)

1. **Data readiness**
   - Parse dates, normalize ratings, unify attraction IDs/names, deduplicate, identify nationality of users, demographic information.
   - Language detection; translate or handle multilingual text appropriately.
2. **Text processing** (this OPTIONAL - not required)
   - Clean text (lowercase, punctuation, stopwords); keep emojis if informative.
   - Sentiment analysis (rule-based baseline; transformer if available).
   - Topic modeling (BERTopic/LDA) to surface themes; map themes to policy levers.
3. **Attribution / drivers** (this OPTIONAL - not required)
   - Regress ratings on topic intensities and controls (attraction fixed effects, season).
   - Use SHAP/feature importance to quantify drivers.
4. **Time series & seasonality**
   - Monthly aggregation; STL decomposition; change-point detection for drops/spikes.
5. **Segmentation**
   - Group by language/market, first-time vs repeat (heuristics), family vs solo (heuristics).
6. **Visualization & reporting**
   - League tables, heatmaps, calendar plots, maps (if coordinates available).
7. **Governance**
   - Thresholds for alerts; quarterly review; publish scorecards to stakeholders.

## From Insights to Action

1. **Top 5 urgent fixes** (crowding, safety, cleanliness) with owner and timeline.
2. **Medium-term investments** (accessibility upgrades, interpretation quality).
3. **Marketing messaging** to amplify top-performing experiences by market.
4. **Monitoring**: monthly governance meeting using the city-level Experience Quality Index.
"""